// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtC9zdAuta9vePBnmZBPWxW4UoJd8GRI',
    appId: '1:302883549378:web:d49c5a17834318ea5b0b5b',
    messagingSenderId: '302883549378',
    projectId: 'imagen-923c4',
    authDomain: 'imagen-923c4.firebaseapp.com',
    storageBucket: 'imagen-923c4.appspot.com',
    measurementId: 'G-2NZXV6CTRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfjCQF3SgV2II1LBqFfAwGg8yYB1v_8Q',
    appId: '1:302883549378:android:3df0ab7db651db325b0b5b',
    messagingSenderId: '302883549378',
    projectId: 'imagen-923c4',
    storageBucket: 'imagen-923c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRVoaDX6DsOZ2AGEGKRdc17oVSQfhFhY',
    appId: '1:302883549378:ios:c6aa707941e53cc65b0b5b',
    messagingSenderId: '302883549378',
    projectId: 'imagen-923c4',
    storageBucket: 'imagen-923c4.appspot.com',
    iosClientId: '302883549378-m2nivt2kpudb8udhnd3rqoov2ki4p4a9.apps.googleusercontent.com',
    iosBundleId: 'com.imagen.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQRVoaDX6DsOZ2AGEGKRdc17oVSQfhFhY',
    appId: '1:302883549378:ios:c08bafc49821525f5b0b5b',
    messagingSenderId: '302883549378',
    projectId: 'imagen-923c4',
    storageBucket: 'imagen-923c4.appspot.com',
    iosClientId: '302883549378-r9rl235ec7n1merq9io169t9n167l26d.apps.googleusercontent.com',
    iosBundleId: 'com.imagen.macos.RunnerTests',
  );
}
